site_name: Siddhi-IO-Hl7
site_description: Siddhi IO Hl7 Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-io-hl7/
Extra_css:
  - stylesheets/extra.css
Extra_javascript:
  - javascripts/extra.js
repo_name: Siddhi-IO-hl7
repo_url: https://github.com/wso2-extensions/siddhi-io-hl7
copyright: Copyright &copy; 2011 - 2019 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
  - UA-103065-28
  - auto
extra:
  social:
    - type: github
      link: https://github.com/wso2/siddhi
    - type: linkedin
      link: https://www.linkedin.com/groups/13553064
Pages:
  - Welcome: index.md
  - API Docs:
  - License: license.md
